version: '3.6'
services:
  php:
    build: 'php'
    volumes:
      - './src:/var/www/code'
      - './conf/php.ini:/usr/local/etc/php/php.ini'
  nginx:
    image: 'nginx'
    ports:
      - '80:80'
    volumes:
      - './src:/var/www/code'
      - './conf/default.conf:/etc/nginx/conf.d/default.conf'
  database:
    image: mariadb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=bdd
      - MYSQL_USER=saidou
      - MYSQL_PASSWORD=saidou!
  adminer:
    image: adminer
    ports:
      - '8081:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=database
      - ADMINER_DESIGN=brade